CRTL + SPACE -- SELECIONE COLUNA
Shift + SPACE -- SELECIONE LINHA 
CRTL + Shift + SPACE -- SELECIONE TABELA
CRTL + Shift + '+' -- NOVA COLUNA / LINHA
CRTL + '-' -- REMOVER COLUNA / LINHA
CRTL + E -- AUTOCOMPLETAR
