/*
    1ª DEFINIR OBJETIVO
    2ª ESCOLHER OS DADOS NO PRINCÍPIO 80/20
    3ª COMO OS 80% AFETAM OS INDICADORES
    4ª VISUALIZAÇÃO DE DADOS PARA ANALISE
    5ª QUESTIONAR E ENTENDER OS DADOS
    6ª CONFIRMAR OS DADOS
*/

CASE DE SITUAÇÃO: AJUDAR UMA FÁBRICA A AUMENTAR A PRODUTIVIDADE 

-- 1ª DEFINIR OS OBJETIVOS
    DEFINIR AS PRINCIPAIS PERGUNTAS: "POR QUE O LUCRO AUMENTOU / CAIU?"
    QUAIS PROBLEMAS QUERO RESOLVER: "A RECEITA CAIU?" "OS CUSTOS AUMENTARAM?"
    OBJETIVO: AUMENTAR A LUCRATIVIDADE DA EMPRESA
    ENTENDER O NEGÓCIO DA INSTITUIÇÃO!

-- 2ª ESCOLHER OS DADOS NO PRINCÍPIO 80/20
QUAIS SÃO OS FATORES MAIS RELEVANTES QUE INFLUENCIAM OS DADOS E INDICADORES
