CRTL + SPACE -- SELECIONE COLUNA
Shift + SPACE -- SELECIONE LINHA 
CRTL + Shift + SPACE -- SELECIONE TABELA
CRTL + T -- SELECIONAR A TABELA
CRTL + Shift + '+' -- NOVA COLUNA / LINHA
CRTL + '-' -- REMOVER COLUNA / LINHA
CRTL + E -- AUTOCOMPLETAR
F5 -- BUSCAR
CRTL + Shift + L -- FILTRO
ALT + Seta Baixo -- SELECIONAR FILTRO
CRTL + PAGE UP -- ABA DA ESQUERDA
CRTL + PAGE DOWN -- ABA DA DIREITA
CRTL + ALT + T -- TABELA DINÂMICA
CRTL + 1 -- PERSONALIZAR FONTE E ALINHAMENTO
ALT + F1 -- GRÁFICO RÁPIDO
TECLAS ALT -- PARA MAPEAR


SOMA
SE
SEEROR
PROCV
SUBTOTAL
