CRTL + SPACE -- SELECIONE COLUNA
Shift + SPACE -- SELECIONE LINHA 
CRTL + Shift + SPACE -- SELECIONE TABELA
CRTL + T -- SELECIONAR A TABELA
CRTL + Shift + '+' -- NOVA COLUNA / LINHA
CRTL + '-' -- REMOVER COLUNA / LINHA
CRTL + E -- AUTOCOMPLETAR
F5 -- BUSCAR
CRTL + Shift + L -- FILTRO
CRTL + ALT + L -- REAPLICAR FILTRO
CRTL + Shift + A -- INSERIR FUNÇÃO
ALT + Seta Baixo -- SELECIONAR FILTRO
CRTL + PAGE UP -- ABA DA ESQUERDA
CRTL + PAGE DOWN -- ABA DA DIREITA
CRTL + ALT + T -- TABELA DINÂMICA
CRTL + 1 -- PERSONALIZAR FONTE E ALINHAMENTO
ALT + F1 -- GRÁFICO RÁPIDO
Shift + SPACE + Mouse -- MOVER E COLOCA UMA LINHA ENTRE DOIS REGISTROS 
CRTL + ; -- DIA
CRTL + Shift + ; -- HORA DE ATUALIZAÇÃO
TECLAS ALT -- PARA MAPEAR
F4 -- TRUNCATE
ALT + = -- SOMA RÁPIDA
CRTL + D -- DUPLICAR
CRTL + F3 -- GERERNCIADOR DE NOMES


INDIRETO
SOMA
SE
SEEROR
PROCV
SUBTOTAL
ÍNDICE
CORRESP
MAX
MIN
MAIOR
MENOR
CONT.VALORES
CONT.NUM
CONT.VAZIO
CONT.SE
E

=SEERRO(SE(PROCV($B$7;Base!D:D;1;0)=$B$7;"Encontrado");"Não encontrado")
=CONT.SES(A:A;A1)<2
=CONT.SES(E:E;">31/12/2018")
=SE(SOMA($B$2:$B$8)<=$B$11; SOMA($B$2:$B$8); 0)
=SE(OU(B2="";C2="");"";SE(E(B2<>"";C2<>"");B2*C2;""))
=SE(E(B2<>"";C2<>"");B2*C2;"")
=SOMASES($E:$E;$B:$B;"*Alemanha*";$D:$D;"*Puma*")
=SOMASES($E:$E; $D:$D; I$23; $B:$B; $H24)